### ISSUE TITLE
ESC-POS.NET

### ISSUE THREAD

**Issue by leandrovip** [leandrovip/Vip.Printer#10]
Hey Leandro,

Did you try out my library, ESCPOS_NET?  I'd be interested to hear your thoughts and see if you would be interested in using / contributing to my library.  It's pretty straightforward to use.

_Originally posted by @lukevp in https://github.com/leandrovip/Vip.Printer/issues/2#issuecomment-474177884_

**Comment by leandrovip** [comment]
Hey @lukevp, how are you?
I do not test your library, but i will try this as soon as possible and give you feedback, ok? I began this project because was necessary to use esc/bema commands.

**Comment by lukevp** [comment]
Great! What is esc/bema and how's it different from esc/pos?

**Comment by leandrovip** [comment]
ESC/BEMA is a command schema for [Bematech](https://www.bematech.com.br/produtos/equipamentos/) printers. It´s similar in some commands (binary), but have also peculiarities.

**Comment by lukevp** [comment]
Interesting!  This could be implemented in my library by creating another ICommandEmitter that can produce ESC/BEMA instead.  I don't have one of these to test, unfortunately.

**Comment by leandrovip** [comment]
Do you use RawPrinterHelper?
