### ISSUE TITLE
Hoje em dia é possível imprimir diretamente do browser?

### ISSUE THREAD

**Issue by ewertonrfd** [leandrovip/Vip.Printer#15]
Acompanhando um pouco as API dos browser, tenho visto que cada vez mais a web está ganhando permissões que antes não era permitido.
No site: https://permission.site mostra que é possível ter acesso ao USB

Seria então possível um site ter acesso a uma impressora não-fiscal (exemplo a 4200) ?

**Comment by leandrovip** [comment]
Muito provavelmente sim.
Mas não tenho esta informação com certeza.

Precisaria de testar. Caso teste, por favor, informe aqui pra nós.

[]´s

**Comment by ewertonrfd** [comment]
A informação mais relevante sobre o assunto até então que achei foi:
https://www.qz.io/
O link acima mostra um jeito de fazer o que perguntei.
Ainda não funciona de forma tão prática, do estilo **"só fazer o site e funciona em tudo"**, mas com algumas instalações e tudo vai funcionar :) 

Espero que ajude outras pessoas também.

**Comment by leandrovip** [comment]
Show, Ewerton!
Obrigado por compartilhar!

[]´s
