### ISSUE TITLE
Daruma, Elgin e versão framework

### ISSUE THREAD

**Issue by marcelokrol** [leandrovip/Vip.Printer#17]
Tenho 2 duvidas:
- Esta funcional para Daruma e Elgin? Percebi que alguns comandos na Epson são diferentes para a Elgin.
- Preciso no framework 4.5 devido a algumas restrições do meu sistema, será que roda se fizer um downgrade?

**Comment by leandrovip** [comment]
1 -Já fiz testes na Elgin I9, todos os comandos foram executados com sucesso. Na daruma ainda não testei, porém se estiver configurado para o set Esc/Pos creio que não haverá problema nenhum.

2- Se fizer o down para o 4.5 irá funcionar sim, sem problemas.
