### ISSUE TITLE
Escopo Esc/Bema

### ISSUE THREAD

**Issue by leandrovip** [leandrovip/Vip.Printer#2]
- [x] Definir escopo e tarefas
---
### Características da Fonte
- [x] Negrito
- [x] Itálico
- [x] Sublinhado
- [x] Expandido
- [x] Condensado

### Tamanho da Fonte
- [x] Normal
- [x] Tamanho 2
- [x] Tamanho 3
- [x] ~~Tamanho 4~~

### Alinhamento
- [x] Esquerda
- [x] Direita
- [x] Centralizado

Obs: todas as funções devem permitir passar texto como parâmetro ou apenas ativar/desativar.

### Guilhotina
- [x] Corte parcial
- [x] Corte Total

### Outras opções
- [x] Abertura da gaveta

### Código de Barras e QRCode
- [x] QRCode
- [x] CODE128
- [x] EAN-13 

### Finalização e Testes
- [x] Teste das funções
- [x] Incluir summary e comentários
- [x] Incluir licença nas classes

**Comment by leandrovip** [comment]
Refatorar nomes do enum PrinterType: Epson para EscPos e Bematech para EscBema

**Comment by lukevp** [comment]
Hey Leandro,

Did you try out my library, ESCPOS_NET?  I'd be interested to hear your thoughts and see if you would be interested in using / contributing to my library.  It's pretty straightforward to use.
