### ISSUE TITLE
Implementar impressão do Logotipo

### ISSUE THREAD

**Issue by leandrovip** [leandrovip/Vip.Printer#20]
Disponibilizar método para impressão do logotipo para EscPos e EscBema.

**Comment by marcosgerene** [comment]
@leandrovip 

Existe alguma novidade/previsão sobre isso ?

**Comment by leandrovip** [comment]
@marcosgerene,

Já tenho uma implementação sobre isso, porém estava sem impressora para testes. Chegou uma hoje. Vou fazer alguns testes e disponibilizo.

**Comment by marcosgerene** [comment]
@leandrovip 
Tenho uma i9 e uma tm-20 para testar.

O @adrbarros tem DR700 lá

**Comment by adrbarros** [comment]
Aqui temos
Elgin i9, Elgin i7 (Escritório)
Epson TM-T20 (Escritório)
Daruma DR700 (Escritório)
PrintID (Escritório)
Tanca TP-650 (Cliente)
Bematech MP 2500, 4000, 4200 (Cliente)
Agora adiquirimos uma pra testes bem baratinha marca EVADIN (Padrão ESC/POS)
Se precisar fazer testes, as impressoras que não temos no escritório pegamos nos clientes
