### ISSUE TITLE
Multi Language Support 

### ISSUE THREAD

**Issue by San-Nabaty** [leandrovip/Vip.Printer#25]
Can this print non english/Latin text like Arabic and Hebrew ?

**Comment by leandrovip** [comment]
Hi,
I think so. What is the encoding your printer to use?

Regards;

**Comment by San-Nabaty** [comment]
I don't have much info about it but what i know it can support non latin if it's sent properly , for example Arabic uses Unicode encoding.

**Comment by leandrovip** [comment]
Yes.
If your printer has encoding Unicode set, it's possible to set the encoding in Printer.cs at line 154.

```c#
// change to Unicode
Encoding.GetEncoding("IBM860").GetBytes(value);
```

Can you make a test?

Regards;

**Comment by San-Nabaty** [comment]
check your inbox leandro@vipsolucoes.com I sent you more details

**Comment by leandrovip** [comment]
Hi, 

I added a new method Append with Encoding property, can you a test at branch **teste-encode**? 👍 

```c#
            var printer = new Printer("PrinterName", PrinterType.Epson);

            printer.Append("Test UNICODE", Encoding.Unicode);
            printer.Append("Test ASCII", Encoding.ASCII);
            printer.Append("Test ASCII", Encoding.UTF8);
            printer.NewLines(3);
            printer.Append("End test :)");
            printer.PartialPaperCut();

            printer.PrintDocument();
```

Regards;
Leandro

**Comment by San-Nabaty** [comment]
Hi, 

I think I will need to have the updated version in order to make the test right ? or did you upload the updated version? 

~San

**Comment by leandrovip** [comment]
Yes, 

https://github.com/leandrovip/Vip.Printer/tree/test-encode

**Comment by leandrovip** [comment]
Anything just let me know.

Regards,
Leandro
