### ISSUE TITLE
Valor para o enum

### ISSUE THREAD

**Issue by marcelokrol** [leandrovip/Vip.Printer#26]
Sugiro a inclusão de um valor para o enum PrinterType, onde desse modo fica mais fácil salvar a configuração da impressora utilizada no PDV.

Sugestão:
 ```
public enum PrinterType
    {
        Bematech = 1,
        Epson = 2,
        Daruma = 3
    }
```

**Comment by leandrovip** [comment]
@marcelokrol,

Jóia, já nesta próxima versão disponibilizo esta alteração.
Obrigado
