### ISSUE TITLE
Impressão em modo paisagem

### ISSUE THREAD

**Issue by joao-moniz** [leandrovip/Vip.Printer#34]
Olá estou precisando fazer a impressora imprimir um boleto, em modo paisagem já vi uns videos de algumas fazendo isso mas não consigo achar nada na internet.
Seu projeto faz isso ou sabe me dizer onde acho essa informação ?

**Comment by leandrovip** [comment]
Olá!

Ainda não tem a opção de impressão em paisagem.
Creio que seja possível sim alterar o modo de impressão, rotacionar o texto, mas teria que implementar esta funcionalidade. Não tenho certeza se todos os sets de comando tem disponível. Precisaria estudar um pouco os manuais.
