### ISSUE TITLE
[Code128] Problema com impressão de barras

### ISSUE THREAD

**Issue by marcosgerene** [leandrovip/Vip.Printer#35]
No projeto https://github.com/marcosgerene/Gerene.DFe.EscPos que usa este como base "motor" para impressão de DFes, encontrei um problema na leitura do código de barras do SAT. 

Segue xml. Você pode usar qualquer demo para testar.

[CFe35200911111111111111591234567890001071072281.zip](https://github.com/leandrovip/Vip.Printer/files/5224705/CFe35200911111111111111591234567890001071072281.zip)

---

Teste para ver se estou mandando os dados corretos:
![image](https://user-images.githubusercontent.com/15945003/93208692-546c5500-f733-11ea-9e88-0b584439b159.png)

Resultado da impressão:
![WhatsApp Image 2020-09-15 at 09 12 25](https://user-images.githubusercontent.com/15945003/93208843-9ac1b400-f733-11ea-986d-e02b63a7cfee.jpeg)

Resultado da leitura das barras (testei com 2 leitores).
Linha 1: 51535048485749494949494949494949494949495357
Linha 2: 49505152535455565748484849485549485550505649

**Comment by marcosgerene** [comment]
@leandrovip 
Alguma novidade sobre o bug? Posso ajudar de alguma forma? (Tenho uma TM-20 e uma Elgin i9 para testes).

**Comment by leandrovip** [comment]
> @leandrovip
> Alguma novidade sobre o bug? Posso ajudar de alguma forma? (Tenho uma TM-20 e uma Elgin i9 para testes).

@marcosgerene, 
Por enquanto não tenho novidade, fiquei ausente alguns dias (minha filha nasceu!) e não consegui ver nada sobre este problema. Volto esta semana e já verifico o que está acontecendo.

**Comment by marcosgerene** [comment]
@leandrovip 

Parabéns cara! Desejo muita saúde para sua filha, abração

**Comment by leandrovip** [comment]
@marcosgerene 

Poderia fazer um teste (#36) antes de eu subir a atualização?
Fiz o teste em uma ElginI9 e Dimep Dual, nas duas imprimiu e leu corretamente, caso ok já faço o merge.

Obrigado

**Comment by marcosgerene** [comment]
@leandrovip 

Cara, não vi sua resposta, me desculpa... eu só consigo na segunda-feira, estou sem impressora aqui..

**Comment by leandrovip** [comment]
Tranquilo, aguardo!

[]´s

**Comment by leandrovip** [comment]
Fiz o teste em outras impressoras e o código foi impresso corretamente, mas, qualquer coisa só avisar!

[]´s

**Comment by marcosgerene** [comment]
@leandrovip 

Fiquei fora ontem e hoje, implantação.

Vou testar e te dou o feedbac, abraço
