### ISSUE TITLE
Erro no método WriteLine

### ISSUE THREAD

**Issue by thiagovalim** [leandrovip/Vip.Printer#39]
Se você usar o método NewLine() ele pula duas linhas e não apenas uma, devido ao fato que o método NewLine chama o método WriteLine que também adiciona o caracter \n

public void NewLine()
        {
            WriteLine("\n");
        }

**Comment by leandrovip** [comment]
@thiagovalim,

Observe a imagem em anexo:
Na impressão 1 está como atual, com o `WriteLine("\n")`, tenho o retorno como o esperado, é pulado 1 linha 'completa', e não somente alterado o 'carro de impressão' para a linha de baixo.

Na impressão 2, alterei o método NewLine() para `WriteLine("")` e já não tenho o retorno esperado, a impressão é feita na linha debaixo, e não ocorre o pulo completo como é o esperado por este método.

Obs: Testes em uma Dual Print DIMEP, Bematech 2500, Elgin I9.

Qual o retorno que gostaria obter? Em qual impressora você fez o teste?

![teste-newline](https://user-images.githubusercontent.com/13607586/107045571-6c0cae80-67a4-11eb-9249-75553caf5b52.jpeg)

[]s

**Comment by thiagovalim** [comment]
@leandrovip No caso eu fiz o teste na bematech MP 4200 e daruma DR800 o método NewLine() pula duas linhas seguidas semelhante a primeira imagem (pulou duas linhas entre a linha 2 e 3, pois ao chamar o método NewLine() ele chama o método WriteLine() com \n ficando: \n\n o que faz com que pule duas linhas. O retorno esperado era pular apenas uma linha, o que pode ser feito com Write("\n")

**Comment by leandrovip** [comment]
Jóia, vou fazer um update.

**Comment by leandrovip** [comment]
Atualizado, obrigado!
[]´s
