### ISSUE TITLE
QRCode com texto lateral

### ISSUE THREAD

**Issue by Dufayel** [leandrovip/Vip.Printer#48]
Bom dia, existe alguma forma de alinha o QRCode a esquerda e escrever no espaço a direita do mesmo?
Como no exemplo da imagem abaixo?
![image](https://user-images.githubusercontent.com/11709293/129192472-88a370b3-f6be-432a-bd00-fae8ccafa5ef.png)

**Comment by leandrovip** [comment]
Bom dia! No momento não, mas assim que puder vou verificar a possiblidade de implementar! 

[]´s

**Comment by Dufayel** [comment]
Show de bola, e parabéns pela biblioteca, super completa e fácil de usar!

**Comment by leandrovip** [comment]
Show, fico feliz em saber! Muito obrigado! 

[]´s
