### ISSUE TITLE
A elgin i9 usa o type = PrinterType.Epson 

### ISSUE THREAD

**Issue by ewertonrfd** [leandrovip/Vip.Printer#49]
Bom dia,
Olá @leandrovip 

Me confirma uma informação por favor, **a Elgin usa o type: PrinterType.Epson**   certo?
Vi algunas exemplos e está com esse type
Só por curiosidade (ou alguma coisa que não me atentei ainda) _porque a Elgin não tem um type próprio_? Elas internamente usam o mesmo comandos no caso?

Obrigado desde já

**Comment by ewertonrfd** [comment]
Realmente alguma coisa que não tinha me atentado mesmo 😄 

**Essa imagem responde** 
![2021-08-25](https://user-images.githubusercontent.com/13201575/130788673-178b02b9-1967-4cc4-9b0c-f5c34ff2f8d7.png)

A dúvida veio quando fui explicar outra pessoa, mas agora me atentei melhor a imagem 👍 

Só uma sugestão os type poderia refletir melhor os comandos em vez das marcas (apesar que indiretamente isso já é feito né, as marcas criaram os seus comandos internos e outras marcas usam esses comandos), só uma sugetsão mesmo

**Comment by leandrovip** [comment]
Olá! 
Sim, PrinterType.Epson = EscPos, tem este nome porque a epson que criou este padrão e é o que vem sendo utilizado pela maioria das impressoras. Para Bematech e Daruma, em alguns modelos, é possível setar em suas configurações para utilizar o set EscPos, porém como existem algumas particularidades do próprio modelo, resolvi criar o estes set´s de comando separado. 

Creio que a tendencia, para novos modelos de impressora/marca é continuar utilizando o EscPos como set de comando principal, portanto o PrinterType.Epson seria utilizado ✌

[]´s

**Comment by ewertonrfd** [comment]
Valeu 👍
