### ISSUE TITLE
Converter o Projeto para o Net Core 5+++

### ISSUE THREAD

**Issue by mvidaldev** [leandrovip/Vip.Printer#52]
Bom dia, no que podemos ajudar para converter o projeto para o Net Core?

**Comment by leandrovip** [comment]
Opa, tudo bem?

A biblioteca tem suporte a .Net Standard então funciona bem em projetos .Net Core, 5. Já fiz alguns testes e funcionou sem problemas.

Caso dê alguma mensagem de erro referente ao Encoding utilizado pela biblioteca então será necessário adicionar esta linha abaixo na inicialização do seu projeto (program/main/etc).

```csharp
Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);
```
De resto o funcionamento é o mesmo 👍🏼

[]´s
