### ISSUE TITLE
Dúvida: Tamanho da Fonte

### ISSUE THREAD

**Issue by MartinPessoa** [leandrovip/Vip.Printer#53]
Boa tarde blz?

Estou desenvolvendo uma aplicação pra um cliente, infelizmente não tenho como ter acesso direto a impressora térmica dele.

Enviei uma aplicação pra ele fazer um teste, funcionou perfeito. Porém ele perguntou se eu podia aumentar o tamanho da fonte.

No Readme.md aqui diz que nas funcionalidades disponíveis, tem o Tamanho da Fonte. Mas eu não consegui encontrar nem no pacote Nugget que eu instalei, nem aqui no demo da library a opção de escolher Tamanho da Fonte.

- Está implementada a função ESCPOS pra escolher tamanho da fonte? Se sim, como faria com esta library?
- Condensed e Expanded são tamanhos de fonte? Tipo `ExpandedMode(PrinterModeState.On)` seria pra ativar um tamanho de fonte maior? Desculpa se a pergunta não faz sentido, é que nunca mexi com impressoras térmicas antes.

Desde já agradeço o retorno e muito obrigado pela ótima library!

**Comment by leandrovip** [comment]
Olá, boa tarde! Tudo bem e contigo?

De que forma você gostaria de aumentar a fonte?

Sim, com o método ExpandedMode() você pode ativar a fonte expandida que aumenta consideravelmente a fonte, porém diminui a quantidade de colunas que você pode utilizar.

Ha os métodos DoubleWidth2(), DoubleWidth3() e NormalWidth() que também alteram o tamanho e largura da fonte, com a mesma premissa de utilizar uma menor quantidade de colunas.

Usando o código:

```csharp
var printer = new Printer('CaminhoNomeImpressora', PrinterType.Epson);
printer.TestPrinter();
printer.PrintDocument();
```

Você consegue observar os tamanhos que podem ser alterados. Em caso de dúvidas me avise por favor.

Abs
