### ISSUE TITLE
Problemas com palavras com assento

### ISSUE THREAD

**Issue by meciasbueno** [leandrovip/Vip.Printer#55]
Estou tendo problemas com palavras com assento, está imprimindo um caracter "especial" no lugar.
Como resolvo isso? no meu caso é português.

**Comment by leandrovip** [comment]
Olá! 

Qual o modelo impressora? 
Qual o set de comando utilizado? 
Imprime o auto-test da impressora e veja qual é o charset configurado?

Obs: Geralmente é por conta do charset ou pelo encoding do conteúdo.

[]´s

**Comment by meciasbueno** [comment]
> Olá!
> 
> Qual o modelo impressora? Qual o set de comando utilizado? Imprime o auto-test da impressora e veja qual é o charset configurado?
> 
> Obs: Geralmente é por conta do charset ou pelo encoding do conteúdo.
> 
> []´s

Está ocorrendo na minha impressora de teste (Portatil Mobile Printer), nesta eu não consegui imprimir o auto test, não sai nada. Na especificação dela aparece ANK: caracteres ANK.

Na impressora do cliente também está acontecendo problemas com assento, é a Bematech MP 4200 TH

**Comment by leandrovip** [comment]
Na sua impressora de teste, acredito que seja por questão do chartset/encoding. O conteúdo que está enviando está como? UTF8? ASCII?

Na MP4200, você pode conferir a configuração imprimindo o auto-teste ou através do software 'Bematech User Software', pois se for preciso você consegue alterar. 

Geralmente deixo configurado nestas impressoras (4200) o charset IBM850 (salvo engano)
