### ISSUE TITLE
Acentos

### ISSUE THREAD

**Issue by edsonfast** [leandrovip/Vip.Printer#59]
Olá,

Como faço para imprimir com acentos na EPSON TM-T20X? notei que algumas vezes a impressão é com acento, mas não identifiquei como.

Att.
Edson

**Comment by leandrovip** [comment]
Você esta utilizando algum encoding específico? Qual o encoding utilizado pela impressora? Foi alterado alguma configuração padrão?

[]´s

**Comment by edsonfast** [comment]
É uma aplicação WPF em C#, não fiz alteração na configuração da impressora e também não defino encoding, vou testar de outras formas, obrigado por enquanto
